management:
	docker-compose up -d

hazelcast:
	COMPOSE_PROFILES=full docker-compose up -d

stop:
	COMPOSE_PROFILES=full docker-compose stop

clean:
	COMPOSE_PROFILES=full docker-compose down -v
